export function toModificacionPoaItem(mod: any) {
  return {
    id: mod.id,
    numero: mod.numero,
    estado: mod.estado,
    motivo: mod.motivo,
    observaciones: mod.observaciones,
    observacionBienes: mod.observacionBienes,
    tipoDiscrepancia: mod.tipoDiscrepancia,
    periodoFiscalId: mod.periodoFiscalId,
    actividadOrigenId: mod.actividadOrigenId,
    informeRuta: mod.informeRuta,
    nuevaPoaVersionId: mod.nuevaPoaVersionId,
    nuevaActividadId: mod.nuevaActividadId,
    anterior: {
      programaCodigo: mod.programaCodigoAnterior,
      programaNombre: mod.programaNombreAnterior,
      actividadCodigo: mod.actividadCodigoAnterior,
      actividadNombre: mod.actividadNombreAnterior,
      itemCodigo: mod.itemCodigoAnterior,
      itemNombre: mod.itemNombreAnterior,
      fuenteCodigo: mod.fuenteCodigo,
      fuenteNombre: mod.fuenteNombre,
      responsableId: mod.responsableAnteriorId,
      responsableNombre: mod.responsableAnteriorNombre,
      montoPlanificado: Number(mod.montoPlanificadoAnterior),
    },
    nuevo: {
      programaCodigo: mod.programaCodigoNuevo,
      programaNombre: mod.programaNombreNuevo,
      actividadCodigo: mod.actividadCodigoNuevo,
      actividadNombre: mod.actividadNombreNuevo,
      itemCodigo: mod.itemCodigoNuevo,
      itemNombre: mod.itemNombreNuevo,
      fuenteCodigo: mod.fuenteCodigo,
      fuenteNombre: mod.fuenteNombre,
      responsableId: mod.responsableNuevoId,
      responsableNombre: mod.responsableNuevoNombre,
      montoPlanificado: Number(mod.montoPlanificadoNuevo),
    },
    solicitante: mod.solicitante,
    analista: mod.analista,
    director: mod.director,
    createdAt: mod.createdAt,
    updatedAt: mod.updatedAt,
  };
}
