export function toListItem(c: any) {
  return {
    id: c.id,
    tipo: c.tipo,
    numero: c.numero,
    estado: c.estado,
    monto: Number(c.monto),
    conIva: c.conIva,
    observaciones: c.observaciones,
    cedulaVersionId: c.cedulaVersionId,
    unidadRequirenteId: c.unidadRequirenteId,
    poaVersionId: c.poaVersionId,
    fechaSolicitud: c.fechaSolicitud,
    fechaSuscripcion: c.fechaSuscripcion,
    fechaUso: c.fechaUso,
    devueltaPorFinanciero: c.devueltaPorFinanciero,
    createdAt: c.createdAt,
    updatedAt: c.updatedAt,
    actividad: c.actividad ? {
      id: c.actividad.id,
      programaCodigo: c.actividad.programaCodigo,
      programaNombre: c.actividad.programaNombre,
      actividadCodigo: c.actividad.actividadCodigo,
      actividadNombre: c.actividad.actividadNombre,
      itemCodigo: c.actividad.itemCodigo,
      itemNombre: c.actividad.itemNombre,
      fuenteCodigo: c.actividad.fuenteCodigo,
      fuenteNombre: c.actividad.fuenteNombre,
      saldoDisponible: Number(c.actividad.saldoDisponible),
      periodoFiscalId: c.actividad.poaVersion?.periodoFiscalId,
      periodoAnio: c.actividad.poaVersion?.periodoFiscal?.anio,
    } : null,
    solicitante: c.solicitante,
    analista: c.analista,
    director: c.director,
    documentos: (c.documentos || []).map((doc: any) => ({
      id: doc.id,
      tipo: doc.tipo,
      nombreOriginal: doc.nombreOriginal,
      tamano: doc.tamano,
      mimeType: doc.mimeType,
      plantilla: doc.plantilla,
      versionPlantilla: doc.versionPlantilla,
      hashDocumento: doc.hashDocumento,
      createdAt: doc.createdAt,
    })),
  };
}
